src/Entity/Messages.php
<?php

namespace App\Entity;

use App\Repository\MessagesRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=MessagesRepository::class)
 */
class Messages
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text")
     */
    private $message;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\Column(type="boolean")
     */
    private $is_read = 0;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="sent")
     * @ORM\JoinColumn(nullable=false)
     */
    private $sender;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="received")
     * @ORM\JoinColumn(nullable=false)
     */
    private $recipient;

    public function __construct()
    {
        $this->created_at = new \DateTime();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getMessage(): ?string
    {
        return $this->message;
    }

    public function setMessage(string $message): self
    {
        $this->message = $message;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getIsRead(): ?bool
    {
        return $this->is_read;
    }

    public function setIsRead(bool $is_read): self
    {
        $this->is_read = $is_read;

        return $this;
    }

    public function getSender(): ?User
    {
        return $this->sender;
    }

    public function setSender(?User $sender): self
    {
        $this->sender = $sender;

        return $this;
    }

    public function getRecipient(): ?User
    {
        return $this->recipient;
    }

    public function setRecipient(?User $recipient): self
    {
        $this->recipient = $recipient;

        return $this;
    }
}

src/Form/MessagesType.php
<?php

namespace App\Form;

use App\Entity\Messages;
use App\Entity\User;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class MessagesType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title', TextType::class, [
                "attr" => [
                    "class" => "form-control"
                ]
            ])
            ->add('message', TextareaType::class, [
                "attr" => [
                    "class" => "form-control"
                ]
            ])
            ->add('recipient', EntityType::class, [
                "class" => User::class,
                "choice_label" => "email",
                "attr" => [
                    "class" => "form-control"
                ]
            ])
            ->add('envoyer', SubmitType::class, [
                "attr" => [
                    "class" =>  "btn btn-primary"
                ]
            ]);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Messages::class,
        ]);
    }
}

src/Controller/MessagesController.php
<?php

namespace App\Controller;

use App\Entity\Messages;
use App\Form\MessagesType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bridge\Twig\Mime\TemplatedEmail;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Mailer\MailerInterface;


class MessagesController extends AbstractController
{
    /**
     * @Route("/messages", name="messages")
     */
    public function index(): Response
    {
        return $this->render('messages/index.html.twig', [
            'controller_name' => 'MessagesController',
        ]);
    }

    /**
     * @Route("/send", name="send")
     *
     */
    public function send(Request $request, EntityManagerInterface $entityManager, MailerInterface $mailer): Response
    {
        $message = new Messages;

        $form = $this->createForm(MessagesType::class, $message);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isSubmitted()) {
            $message->setSender($this->getUser());

            $entityManager->persist($message);
            $entityManager->flush();

            //Envoi d'email
            $email = (new TemplatedEmail())
                ->from($message->getSender()->getEmail())
                ->to('osba@gmail.com')
                ->subject($message->getTitle())
                ->text($message->getMessage())
                ->htmlTemplate('emails/message.html.twig')

                // pass variables (name => value) to the template
                ->context([

                    "message" => $message
                ]);

            $mailer->send($email);

            $this->addFlash("message", "Message envoyé avec succés");
            return $this->redirectToRoute("messages");
        }

        return $this->render("messages/send.html.twig", [
            "form" => $form->createView()

        ]);
    }

    /**
     * @Route("/received", name="received")
     */
    public function received(): Response
    {
        return $this->render('messages/received.html.twig');
    }

    /**
     * @Route("/read/{id}", name="read")
     */
    public function read(Messages $message, EntityManagerInterface $entityManager): Response
    {
        $message->setIsRead(true);

        $entityManager->persist($message);
        $entityManager->flush();

        return $this->render('messages/read.html.twig', compact("message"));
    }
}

templates/messages/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Messagerie
{% endblock %}

{% block body %}
	<div>
		<h1>Messagerie</h1>
	</div>

	<table class="table">
		<thead>
			<tr>
				<th scope="col">Reçus</th>
				<th scope="col">Envoyés</th>
				<th scope="col">Dossiers</th>

			</tr>
		</thead>
		<tbody>
			<tr>
				<td>{{ app.user.received|length }}</td>
				<td>{{ app.user.sent|length }}</td>

				<td>
					<a class="btn btn-primary" data-bs-toggle="offcanvas" href="#offcanvasExample" role="button" aria-controls="offcanvasExample">
						Mes dossiers
					</a>
					<a href="{{ path("send") }}" class="btn btn-primary">Envoyer un message</a>

				</td>
			</tr>
		</tbody>
	</table>

	<div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasExample" aria-labelledby="offcanvasExampleLabel">
		<div class="offcanvas-header">
			<h2 class="offcanvas-title" id="offcanvasExampleLabel">Mes dossiers</h2>
			<button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
		</div>
		<div class="offcanvas-body">
			<div class="list-group">
				<a href="{{ path("messages") }}" class="list-group-item list-group-item-action active">Accueil</a>
			</div>
			<div class="list-group">
				<a href="{{ path("received") }}" class="list-group-item list-group-item-action">Boîte de reception</a>
			</div>
			<div class="list-group">
				<a href="{{ path("messages") }}" class="list-group-item list-group-item-action">Messages envoyés</a>
			</div>

		</div>
	</div>


{% endblock %}

templates/messages/read.html.twig
{% extends 'base.html.twig' %}

{% block title %}Messagerie
{% endblock %}

{% block body %}
	<div>
		<h1>Messagerie</h1>
		<div class="boutons">
			<div class="btndossier">
				<a class="btn btn-primary" data-bs-toggle="offcanvas" href="#offcanvasExample" role="button" aria-controls="offcanvasExample">
					Mes dossiers
				</a>
			</div>
			<div class="btnboite">
				<a class="btn btn-primary" href="{{path("received")}}">
					Boîte de réception
				</a>
			</div>
		</div>

		<div class="unmessage">

			<p class="fw-bold titre">
				{{ message.title }}</p>

			<p class="sender">Message de :
				{{ message.sender.email }}</p>

			<p class="date">Le :
				{{ message.createdAt|date('d-m-Y H:i:s')}}</p>


			<div class="contenu">Contenu du message :

				{{ message.message }}
			</div>
		</div>

	</div>
</div>
<div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasExample" aria-labelledby="offcanvasExampleLabel">
	<div class="offcanvas-header">
		<h2 class="offcanvas-title" id="offcanvasExampleLabel">Mes dossiers</h2>
		<button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
	</div>
	<div class="offcanvas-body">
		<div class="list-group">
			<a href="{{ path("messages") }}" class="list-group-item list-group-item-action">Accueil</a>
		</div>
		<div class="list-group">
			<a href="{{ path("received") }}" class="list-group-item list-group-item-action active">Boîte de reception</a>
		</div>
		<div class="list-group">
			<a href="{{ path("messages") }}" class="list-group-item list-group-item-action">Messages envoyés</a>
		</div>

	</div>
</div>{% endblock %}

templates/messages/received.html.twig
{% extends 'base.html.twig' %}

{% block title %}Messagerie
{% endblock %}

{% block body %}
	<div>
		<h1>Boîte de réception</h1>
		<p>Vous avez reçu
			{{ app.user.received|length }}
			{% if app.user.received|length > 1 %}
				messages
			{% else %}
				message
			{% endif %}

		</p>
	</div>

	<table class="table">
		<thead>
			<tr>
				<th scope="col">De</th>
				<th scope="col">Sujet</th>
				<th scope="col">Date</th>
				<th scope="col">Action</th>

			</tr>
		</thead>
		<tbody>
			{% for message in app.user.received %}
				{% set bold = "" %}
				{% if message.isRead == 0 %}
					{% set bold = "fw-bold" %}
				{% endif %}

				<tr>
					<td class="{{ bold }}">{{ message.sender.email }}</td>
					<td class="{{ bold }}">
						<a href="{{ path("read", {id: message.id}) }}">
							{{ message.title }}</a>
					</td>

					<td class="{{ bold }}">{{ message.createdAt|date }}</td>
				</tr>

			{% endfor %}

			<a class="btn btn-primary" data-bs-toggle="offcanvas" href="#offcanvasExample" role="button" aria-controls="offcanvasExample">
				Mes dossiers
			</a>

		</tbody>
	</table>

	<div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasExample" aria-labelledby="offcanvasExampleLabel">
		<div class="offcanvas-header">
			<h2 class="offcanvas-title" id="offcanvasExampleLabel">Mes dossiers</h2>
			<button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
		</div>
		<div class="offcanvas-body">
			<div class="list-group">
				<a href="{{ path("messages") }}" class="list-group-item list-group-item-action">Accueil</a>
			</div>
			<div class="list-group">
				<a href="{{ path("received") }}" class="list-group-item list-group-item-action active">Boîte de reception</a>
			</div>
			<div class="list-group">
				<a href="{{ path("messages") }}" class="list-group-item list-group-item-action">Messages envoyés</a>
			</div>

		</div>
	</div>


{% endblock %}

templates/messages/send.html.twig
{% extends 'base.html.twig' %}

{% block title %}Messagerie
{% endblock %}

{% block body %}
	<div>
		<h1>Envoyer un message</h1>

		<div class="formmessage">
			{{ form(form) }}
			</div>

			<table class="table">
				<thead>
					<tr>

						<th scope="col">Dossiers</th>

					</tr>
				</thead>
				<tbody>
					<tr>


						<td>
							<a class="btn btn-primary" data-bs-toggle="offcanvas" href="#offcanvasExample" role="button" aria-controls="offcanvasExample">
								Mes dossiers
							</a>


						</td>
					</tr>
				</tbody>
			</table>

			<div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasExample" aria-labelledby="offcanvasExampleLabel">
				<div class="offcanvas-header">
					<h2 class="offcanvas-title" id="offcanvasExampleLabel">Mes dossiers</h2>
					<button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
				</div>
				<div class="offcanvas-body">
					<div class="list-group">
						<a href="{{ path("messages") }}" class="list-group-item list-group-item-action">Accueil</a>
					</div>
					<div class="list-group">
						<a href="{{ path("received") }}" class="list-group-item list-group-item-action">Boîte de reception</a>
					</div>
					<div class="list-group">
						<a href="{{ path("send") }}" class="list-group-item list-group-item-action">Messages envoyés</a>
					</div>

				</div>
			</div>

		</div>
	{% endblock %}